HandyMate - Microverse Final Capstone
PrantoshB/HandyMate-Frontend pull request #19
Opened 2023-05-30 19:54 UTC by PrantoshB

# Hello There 👋🏽 

![hello](https://media.giphy.com/media/brsEO1JayBVja/giphy.gif)

In this PR, Me (@PrantoshB ), @utsargo , @yetemegn-telaye , @haliljon  and @JacintaNgwu have:

- Created the HandyMate Frontend using React
- Fetched API from the backend and load the data
- Added functionality for authentication via API
- Written Unit Tests using `JEST`
- Customized the website and made it responsive using `BootStrap` and `SCSS`
- Fixed Linters Errors using `StyleLint` and `esLint`
- Followed Git and GitHub Flows

### Backend PR Link
- Here is the PR link of the [Backend](https://github.com/PrantoshB/HandyMate-Backend/pull/25)

### Cheers 🥂 
### Prantosh

2023-05-30 20:44 UTC, Meltrust requested changes
Hi @PrantoshB,

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation, but you are almost there!






### To highlight:

-  Tests are passing✔️
-  Nice code organization ✔️ 
-  App is working well✔️ 
-  Good readme ✔️ 
-  Beautiful frontend ✔️ 



#### You are really close to finishing the Microverse program!! Keep it up! 👍👍👍

![You can do it](https://media.giphy.com/media/FemTGpEZeK27M5fKL4/giphy.gif)

### After implementing the requested changes, please submit another review request. ♻️
_Check the comments under the review._







Cheers and Happy coding!👏👏👏

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the previous reviews unless it is requested otherwise._**

------

2023-05-30 20:44 UTC, Meltrust commented on src/components/SignUp.js
> +      console.log(response.data);
- [ ] According to the javascript general  [best practices](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) requirements:

![image](https://github.com/PrantoshB/HandyMate-Frontend/assets/57421823/2b2ccffe-4a12-4282-ad2a-a3966c328e5c)

Therefore, kindly remove this debugging console.log statement from line 29, so we can meet this particular requirement. 👍

2023-05-30 20:44 UTC, Meltrust commented on src/__mock__/Home.js
> +const Home = () => {
- [ ] When I add some services, the image is overlapping the service type:

![image](https://github.com/PrantoshB/HandyMate-Frontend/assets/57421823/1e667241-3f56-44e0-8810-2a63b86749c6)

Kindly, add some padding/margins so the service type does not overlap with the images from your users.

- [ ] OPTIONAL: You could add some styling to the image containers to make them all the same size to improve the UX. This can be done by making the image containers a set size and stretching the images on those containers.  👍

2023-05-31 02:56 UTC, utsargo commented on src/components/SignUp.js
> +      console.log(response.data);
@Meltrust Thanks for pointing that out. Just fixed that.

2023-05-31 02:57 UTC, utsargo commented on src/__mock__/Home.js
> +const Home = () => {
Fixed.
![Screenshot from 2023-05-31 08-15-22](https://github.com/PrantoshB/HandyMate-Frontend/assets/6623974/b78dabaf-b8c7-4bbc-a61b-7042f549f26b)

2023-05-31 05:17 UTC, Meltrust approved these changes
#### Hi @PrantoshB,


# **Wow, you did it 🎉**
![Brilliant](https://media.giphy.com/media/d31w24psGYeekCZy/giphy.gif)
## Thank you for the changes implemented 💪 🥇 ㊗️ 
#### _Unless you want to add more features, go ahead to your final presentation ⏩ ⏩ ⏩_ 
## You are about to finish the Microverse program.  You have come a long way!!!




### Good luck in the software industry!!  I'll see you there. ✨
### **Congratulations!!!!!!**  🎉
![applause](https://media.giphy.com/media/srg19CG0cKMuI/giphy.gif)

### To highlight

- Debugging code has been removed✔️ 
- Main page items have been styled for more consistency ✔️ 
- Great job✔️ 



Cheers and Happy coding!👏👏👏


------

2023-06-02 14:33 UTC, merged